### ISSUE TITLE
rmsf: API reference page missing? per-residue?

### ISSUE THREAD

**Issue by envirodug** [Amber-MD/pytraj#1397]
There is a tutorial on using pt.rmsf() on trajectories (http://amber-md.github.io/pytraj/latest/tutorials/rmsf.html), which shows how to perform the analysis on all atoms.  Instead of performing the calculation on a per-atom basis, I'd like to do it on a per-residue basis — but I could not find the corresponding API reference page to figure out how to do this.

**Comment by hainm** [comment]
my bad. it's alias of `atomicfluct` command in cpptraj. Please see the docs there

https://github.com/Amber-MD/pytraj/blob/master/pytraj/all_actions.py#L1368

**Comment by hainm** [comment]
In Ipython or Jupyter notebook, you can always read the docs via 

```python
pt.rmsf? # then Enter
```

**Comment by envirodug** [comment]
Thanks.  When I try to use the mask '@CA', the rmsf calculation still seems to perform the analysis on all atoms.  Is this the correct way to do this? 

`pt.rmsf(traj, '@CA')`
or 
`pt.rmsf(traj, mask='@CA')`

**Comment by envirodug** [comment]
Or maybe it's just reporting the same @CA rmsf values for all atoms within a residue?  Because the calculation plot output looks different if I include or exclude @CA, but the number of atoms displayed in the plot remains the same (>4000).

**Comment by hainm** [comment]
1. Can you turn on the verbose and post the log here?

```python
pt._verbose(True)
traj = pt.load(...) # or iterload
pt.rmsf(traj, '@CA') # mask='@CA' is similiar
```

2. Can you reproduce the output in its example?
```python
  | >>> import pytraj as pt
  | >>> traj = pt.datafiles.load_tz2_ortho()
  | >>> data = pt.rmsf(traj, '@CA')
  | >>> data[:3]
  | array([[  5.        ,   0.61822273],
  | [ 16.        ,   0.5627449 ],
  | [ 40.        ,   0.53717119]])
```

**Comment by hainm** [comment]
> Or maybe it's just reporting the same @ca rmsf values for all atoms within a residue? Because the calculation plot output looks different if I include or exclude @ca, but the number of atoms displayed in the plot remains the same (>4000).

I will check tonight.

**Comment by envirodug** [comment]
I see what it is doing.  It's plotting only the CA information, but using the atom numbers instead of residue numbers.  I also tried using options='byres', but the calculation still reports the information by atom numbers instead of residue numbers.  Is this call correct?

`data = pt.rmsf(traj, '@CA', options='byres')`

**Comment by hainm** [comment]
1. can your turn on the cpptraj log like I said earlier?  `pt._verbose(True)`
2. May be running cpptraj and compare?

```
cmd = """
parm your.parm7
trajin your.nc
atomicfluct @CA byres  out test.dat
"""

pt._verbose(True)
state = pt.load_cpptraj_state(cmd)
state.run()

# then check the content of test.dat
```

**Comment by envirodug** [comment]
I am not sure where to find the log information after turning on `pt._verbose(True)`, but I ran the cpptraj command you typed above and information is reported on a per-residue basis in test.dat.  However, if I run the pytraj command specifying `options='byres'`, the output is on a per-atom basis (with data points corresponding to the CA atom number).

**Comment by hainm** [comment]
thanks. 

> I am not sure where to find the log information after turning on pt._verbose(True)

the log is in your terminal, not in the notebook (since the notebook does not know how to capture C++ stdout). If you are using IPython, the log is in your current screen.

>  However, if I run the pytraj command specifying options='byres', the output is on a per-atom basis (with data points corresponding to the CA atom number).

So the only difference is in the atom number? is the output data (the rmsf) correct?

I guess I know what is going on. Will fix in master branch. Thanks.

**Comment by envirodug** [comment]
I updated my previous post with some additional information.  It seems the RMSF values calculated both ways (cpptraj vs. pytraj) are slightly different).

**Comment by hainm** [comment]
thx. Will investigate (and fix) tonight.

**Comment by envirodug** [comment]
Thanks for the tip on where to find the log information.

Command 1 (without options='byres'): 
`data = pt.rmsf(traj, '@CA') # mask='@CA' is similiar`

Log 1: 
`    ATOMICFLUCT: calculating atomic positional fluctuations for atoms.
	Atom mask: [@CA]
	Start: 1  Stop: Final frame
	Mask [@CA] corresponds to 12 atoms.
`

Command 2 (with options='byres'): 
`data2 = pt.rmsf(traj, '@CA', options='byres') # mask='@CA' is similiar`

Log 2: 
`    ATOMICFLUCT: calculating atomic positional fluctuations for atoms.
	Atom mask: [@CA]
	Start: 1  Stop: Final frame
	Mask [@CA] corresponds to 12 atoms.`

The log output is the same for both commands.

**Comment by envirodug** [comment]
I think I might see the problem in the code here:  https://github.com/Amber-MD/pytraj/blob/master/pytraj/all_actions.py#L1368

In the other def calls where options can be specified, there is a line similar to this:
`command = ' '.join((mask, options))`
 
But for `def atomicfluct`, it's just this:
`command = mask`

**Comment by hainm** [comment]
cool. Wanna make your first contribution to pytraj (by making a pull request)? :P

**Comment by envirodug** [comment]
This is the first time I've tried to do this, but I created a fork of the code, made a modification, and submitted a pull request.  Caveat: I haven't tested the change to make sure it works :)  That's the next thing I need to figure out how to do after making a forked change ...

**Comment by hainm** [comment]
you can add the test here:

https://github.com/Amber-MD/pytraj/blob/master/tests/test_analysis/test_atomicfluct.py#L25

```python
def test_RMSF_with_options(self):
    [fill your code here]
```

compare your expected data (like from `load_cpptraj_state` above) to pytraj's output.

You need to submit a pull request to `Amber-MD/pytraj` repo. https://github.com/Amber-MD/pytraj/pulls

**Comment by hainm** [comment]
how to run pytraj tests (after install from source code)

https://github.com/Amber-MD/pytraj/wiki/Run-pytraj-tests

**Comment by envirodug** [comment]
Fixed!

**Comment by hainm** [comment]
I reopen this issue since the website still does not have `rmsf` docs yet.

**Comment by hainm** [comment]
updated: http://amber-md.github.io/pytraj/latest/_api/pytraj.all_actions.html?highlight=rmsf#pytraj.all_actions.rmsf
